sudo: required
services:
  - docker

before_install:
  - docker build -t docker-react -f dockerfile.dev .

script:
  - docker run docker-react npm run test:ci
#   ========
#   AWS stuff

# deploy:
#   provider: elasticbeanstalk
#   region: "us-west-2"
#   app: "docker-app"
#   env: "Docker-env"
#   bucket_name: "blahblahblah"
#   bucket_path: "docker"
#   on:
#     branch: master
